services:
  - type: web
    name: ecommerce_backend
    env: python
    dockerfilePath: Dockerfile
    rootDir: .
    plan: free

    # Start command for running Django with Gunicorn
    #      python manage.py migrate --noinput

    startCommand: |
      gunicorn ecommerce_backend.wsgi:application --bind 0.0.0.0:${PORT:-8000}

    # Environment variables for runtime
    envVars:
      - key: SECRET_KEY
        value: ${SECRET_KEY}
      - key: DATABASE_URL
        value: ${DATABASE_URL}
      - key: DJANGO_ALLOWED_HOSTS
        value: ${DJANGO_ALLOWED_HOSTS}
      - key: DJANGO_CORS_ALLOWED_ORIGINS
        value: ${DJANGO_CORS_ALLOWED_ORIGINS}
      - key: DJANGO_CSRF_TRUSTED_ORIGINS
        value: ${DJANGO_CSRF_TRUSTED_ORIGINS}
      - key: DEBUG
        value: "False"
      - key: CLOUDINARY_URL
        value: ${CLOUDINARY_URL}

    # Build arguments (passed to Dockerfile)
    buildArgs:
      - key: SECRET_KEY
        value: ${SECRET_KEY}
      - key: DATABASE_URL
        value: ${DATABASE_URL}
      - key: DEBUG_BUILD
        value: "False"
      - key: DJANGO_ALLOWED_HOSTS
        value: ${DJANGO_ALLOWED_HOSTS}
      - key: DJANGO_CORS_ALLOWED_ORIGINS
        value: ${DJANGO_CORS_ALLOWED_ORIGINS}
      - key: DJANGO_CSRF_TRUSTED_ORIGINS
        value: ${DJANGO_CSRF_TRUSTED_ORIGINS}
      - key: DJANGO_ENV
        value: production
      - key: CLOUDINARY_URL
        value: ${CLOUDINARY_URL}


