name: CI for Django Backend

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    # Log in to Docker Hub (CONDITIONAL LOGIN)
    # Only log in to Docker Hub if the event is a push to 'main'
    # OR if it's a pull request from the same repository (not a fork).
    # This prevents credentials from being exposed in untrusted fork PRs.
    - name: Log in to Docker Hub
      if: github.event_name != 'pull_request' || github.repository == github.event.pull_request.head.repo.full_name
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }} # Use DOCKER_USERNAME/DOCKER_PASSWORD
        password: ${{ secrets.DOCKER_PASSWORD }}
        registry: docker.io

    - name: Build Docker image for Backend
      run: |
        IMAGE_NAME=${{ secrets.DOCKER_USERNAME }}/ecommerce-backend
        docker build -t ${IMAGE_NAME}:latest --load .

    - name: Run Django Tests in Docker Container
      run: |
        IMAGE_NAME=${{ secrets.DOCKER_USERNAME }}/ecommerce-backend
        docker run -d --name temp_db_for_tests \
          -e POSTGRES_DB=test_db \
          -e POSTGRES_USER=test_user \
          -e POSTGRES_PASSWORD=test_password \
          postgres:16-alpine

        docker run --rm \
          --link temp_db_for_tests:db \
          -e DB_NAME=test_db \
          -e DB_USER=test_user \
          -e DB_PASSWORD=test_password \
          -e DB_HOST=db \
          -e DB_PORT=5432 \
          ${IMAGE_NAME}:latest python manage.py test

        docker stop temp_db_for_tests
        docker rm temp_db_for_tests

    # Push Docker image to Docker Hub (CONDITIONAL PUSH)
    # Only push if the event is a push to 'main'
    # OR if it's a pull request from the same repository (not a fork).
    # This ensures images are only pushed from trusted contexts.
    - name: Push Docker image to Docker Hub
      if: github.event_name != 'pull_request' || github.repository == github.event.pull_request.head.repo.full_name
      run: |
        IMAGE_NAME=${{ secrets.DOCKER_USERNAME }}/ecommerce-backend
        docker push ${IMAGE_NAME}:latest
