name: CI for Django Backend

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    # Log in to Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        # These will print masked values to the log to confirm secrets are being read.
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}
    - name: Debug Docker Hub Username Secret
      run: echo "::add-mask::${{ secrets.DOCKER_HUB_USERNAME }}" && echo "Docker Hub Username (masked): ${{ secrets.DOCKER_HUB_USERNAME }}"
      # Condition to only run if username secret exists (optional, but good practice)
      if: success() || failure() # run regardless of previous step status to see the debug
    - name: Debug Docker Hub Token Secret
      run: echo "::add-mask::${{ secrets.DOCKER_HUB_TOKEN }}" && echo "Docker Hub Token (masked): ${{ secrets.DOCKER_HUB_TOKEN }}"
      # Condition to only run if token secret exists (optional, but good practice)
      if: success() || failure() # run regardless of previous step status to see the debug

    - name: Build Docker image for Backend
      run: |
        IMAGE_NAME=${{ secrets.DOCKER_HUB_USERNAME }}/ecommerce-backend
        docker build -t ${IMAGE_NAME}:latest --load .

    - name: Run Django Tests in Docker Container
      run: |
        IMAGE_NAME=${{ secrets.DOCKER_HUB_USERNAME }}/ecommerce-backend
        docker run -d --name temp_db_for_tests \
          -e POSTGRES_DB=test_db \
          -e POSTGRES_USER=test_user \
          -e POSTGRES_PASSWORD=test_password \
          postgres:16-alpine

        docker run --rm \
          --link temp_db_for_tests:db \
          -e DB_NAME=test_db \
          -e DB_USER=test_user \
          -e DB_PASSWORD=test_password \
          -e DB_HOST=db \
          -e DB_PORT=5432 \
          ${IMAGE_NAME}:latest python manage.py test

        docker stop temp_db_for_tests
        docker rm temp_db_for_tests

    - name: Push Docker image to Docker Hub
      run: |
        IMAGE_NAME=${{ secrets.DOCKER_HUB_USERNAME }}/ecommerce-backend
        docker push ${IMAGE_NAME}:latest
