name: CI for Django Backend

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Check secrets
      run: |
        echo "Username: ${{ secrets.DOCKER_HUB_USERNAME }}"
        echo "Token length: ${#{{ secrets.DOCKER_HUB_TOKEN }}}"

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        registry: docker.io  # Optional, defaults to Docker Hub
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}

    - name: Build Docker image for Backend
      run: |
        IMAGE_NAME=${{ secrets.DOCKER_HUB_USERNAME }}/ecommerce-backend
        docker build -t ${IMAGE_NAME}:latest . --load

    - name: Run Django Tests in Docker Container
      run: |
        IMAGE_NAME=${{ secrets.DOCKER_HUB_USERNAME }}/ecommerce-backend
        docker run -d --name temp_db_for_tests \
          -e POSTGRES_DB=test_db \
          -e POSTGRES_USER=test_user \
          -e POSTGRES_PASSWORD=test_password \
          postgres:16-alpine
        docker run --rm \
          --link temp_db_for_tests:db \
          -e DB_NAME=test_db \
          -e DB_USER=test_user \
          -e DB_PASSWORD=test_password \
          -e DB_HOST=db \
          -e DB_PORT=5432 \
          ${IMAGE_NAME}:latest python manage.py test
        docker stop temp_db_for_tests
        docker rm temp_db_for_tests

    - name: Push Docker image to Docker Hub
      run: |
        IMAGE_NAME=${{ secrets.DOCKER_HUB_USERNAME }}/ecommerce-backend
        docker push ${IMAGE_NAME}:latest
